### ISSUE TITLE
[Bug] Discord changes class name for chat textbox

### ISSUE THREAD

**Issue by GetGet99** [GetGet99/Mica-Discord#11]
To fix, replace this code section (Ctrl + F the comment on top) with this
```css
/* [Typing message box: What Discord does with it]

Have a textbox without top margin

Instead, if we scroll down to the bottom, then there is the padding in the chat messages instead.

No, I don't want that since it will be hard to style later.
*/
.form-3gdLxP, .form-3qe0Ni /* Typing message box */
{
    margin-top: 0px !important;
    padding-top: 16px !important;
}
.form-3gdLxP:before, .form-3qe0Ni:before /* Typing message box */
{
    width: 0px !important;
    height: 0px !important;
}
```
